#!/bin/bash

mkdir src/day$1
touch src/day$1/input.txt
touch src/day$1/test.txt
cat <<EOF >src/day$1/main.ts
import * as readline from "readline";

const rl = readline.createInterface({
  input: process.stdin,
  crlfDelay: Infinity
});

let lines: Array<string> = []
rl.on("line", (line: string) => {
  lines.push(line);
});

rl.on("close", () => {
});
EOF
